# Generated by Django 3.2.19 on 2023-06-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.CharField(max_length=250)),
                ('itemname', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
